using System.Collections.Generic;
using System.Transactions;
using Nodes;
using UnityEngine;

namespace Levels
{
    public class Level
    {
        public string seed;
        public int piecesAmount;
        public bool autoGenerated;
        
        public List<Node> nodes;
    }
}
