using System;
using System.Collections.Generic;
using Nodes;
using UnityEngine;

namespace Levels
{
    [Serializable]
    public class Level
    {
        public string seed;
        [Tooltip("Number of ingredients and bread to be instantiated on random level generation")]
        public int piecesAmount;
        public bool autoGenerated;
        
        public List<Node> nodes;
    }
}
