using System;
using System.Collections.Generic;
using Ingredients;
using UnityEngine;

namespace Levels
{
    [Serializable]
    [CreateAssetMenu(fileName = "SandwichLevel", menuName = "Sandwich/Create Level", order = 0)]
    public class SandwichLevel: ScriptableObject
    {
        [Tooltip("Seed used to generate the same level everytime")]
        public string seed;
        [Tooltip("Number of ingredients and bread to be instantiated on random level generation")]
        public int piecesAmount;
        [Tooltip("Mark true if you want to auto generate this level")]
        public bool autoGenerated;
        [Tooltip("Ingredients that you want on your level, exclude bread")]
        public List<IngredientType> ingredients;
        
        [Tooltip("For manual generated levels, you need to assign ingredient and its position on grid")]
        public List<Ingredient> nodes;
    }
}
